version: 2
updates:
  # ----------------------------------------------#
  #                    Python                     #
  # ----------------------------------------------#
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # ----------------------------------------------#
  #                  Dockerfiles                  #
  # ----------------------------------------------#

  # django local
  - package-ecosystem: "docker"
    directory: "/compose/local/django"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # test-database local
  - package-ecosystem: "docker"
    directory: "/compose/local/test-database"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # django production
  - package-ecosystem: "docker"
    directory: "/compose/production/django"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # postgres production
  - package-ecosystem: "docker"
    directory: "/compose/production/postgres"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # redis production
  - package-ecosystem: "docker"
    directory: "/compose/production/redis"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # traefik production
  - package-ecosystem: "docker"
    directory: "/compose/production/traefik"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
