# https://hub.docker.com/_/ubuntu
# get Ubuntu 18.04
FROM ubuntu:bionic

# setup timezone for tzdata
ARG TIMEZONE
ENV TZ=$TIMEZONE
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Update cache and install dependencies
RUN apt-get update -y && apt-get install -y \
    git \
    osm2pgsql \
    python2.7-minimal \
    python-yaml

# linking python to python2.7
#RUN ln -s /usr/bin/python2.7 /usr/bin/python

# Set the osm2pgsql import cache size in MB.
ARG OSM_IMPORT_CACHE
ENV OSM_IMPORT_CACHE $OSM_IMPORT_CACHE

# https://github.com/gravitystorm/openstreetmap-carto
ARG OSM_CARTO_VERSION
RUN git clone https://github.com/gravitystorm/openstreetmap-carto.git /opt/openstreetmap-carto  && \
    cd /opt/openstreetmap-carto && \
    git fetch --all && \
    git checkout $OSM_CARTO_VERSION

# Add run script
ADD ./start-up.sh /start-up.sh
RUN chmod +x /start-up.sh

WORKDIR /opt/openstreetmap-carto

RUN apt-get install -y

# Clean up APT
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/start-up.sh"]
