CREATE TABLE IF NOT EXISTS "public"."planet_osm_line" (
    "osm_id" bigint,
    "access" text,
    "addr:housename" text,
    "addr:housenumber" text,
    "addr:interpolation" text,
    "admin_level" text,
    "aerialway" text,
    "aeroway" text,
    "amenity" text,
    "barrier" text,
    "bicycle" text,
    "bridge" text,
    "boundary" text,
    "building" text,
    "construction" text,
    "covered" text,
    "foot" text,
    "highway" text,
    "historic" text,
    "horse" text,
    "junction" text,
    "landuse" text,
    "layer" integer,
    "leisure" text,
    "lock" text,
    "man_made" text,
    "military" text,
    "name" text,
    "natural" text,
    "oneway" text,
    "place" text,
    "power" text,
    "railway" text,
    "ref" text,
    "religion" text,
    "route" text,
    "service" text,
    "shop" text,
    "surface" text,
    "tourism" text,
    "tracktype" text,
    "tunnel" text,
    "water" text,
    "waterway" text,
    "way_area" real,
    "z_order" integer,
    "tags" hstore,
    "way" geometry(LineString,3857),
    "valid_since" date,
    "valid_until" date
) WITH (oids = false);

CREATE INDEX "planet_osm_line_index" ON "public"."planet_osm_line" USING btree ("way");


CREATE TABLE IF NOT EXISTS "public"."planet_osm_point" (
    "osm_id" bigint,
    "access" text,
    "addr:housename" text,
    "addr:housenumber" text,
    "admin_level" text,
    "aerialway" text,
    "aeroway" text,
    "amenity" text,
    "barrier" text,
    "boundary" text,
    "building" text,
    "highway" text,
    "historic" text,
    "junction" text,
    "landuse" text,
    "layer" integer,
    "leisure" text,
    "lock" text,
    "man_made" text,
    "military" text,
    "name" text,
    "natural" text,
    "oneway" text,
    "place" text,
    "power" text,
    "railway" text,
    "ref" text,
    "religion" text,
    "shop" text,
    "tourism" text,
    "water" text,
    "waterway" text,
    "tags" hstore,
    "way" geometry(Point,3857),
    "valid_since" date,
    "valid_until" date
) WITH (oids = false);

CREATE INDEX "planet_osm_point_index" ON "public"."planet_osm_point" USING btree ("way");


CREATE TABLE IF NOT EXISTS "public"."planet_osm_polygon" (
    "osm_id" bigint,
    "access" text,
    "addr:housename" text,
    "addr:housenumber" text,
    "addr:interpolation" text,
    "admin_level" text,
    "aerialway" text,
    "aeroway" text,
    "amenity" text,
    "barrier" text,
    "bicycle" text,
    "bridge" text,
    "boundary" text,
    "building" text,
    "construction" text,
    "covered" text,
    "foot" text,
    "highway" text,
    "historic" text,
    "horse" text,
    "junction" text,
    "landuse" text,
    "layer" integer,
    "leisure" text,
    "lock" text,
    "man_made" text,
    "military" text,
    "name" text,
    "natural" text,
    "oneway" text,
    "place" text,
    "power" text,
    "railway" text,
    "ref" text,
    "religion" text,
    "route" text,
    "service" text,
    "shop" text,
    "surface" text,
    "tourism" text,
    "tracktype" text,
    "tunnel" text,
    "water" text,
    "waterway" text,
    "way_area" real,
    "z_order" integer,
    "tags" hstore,
    "way" geometry(Geometry,3857),
    "valid_since" date,
    "valid_until" date
) WITH (oids = false);

CREATE INDEX "planet_osm_polygon_index" ON "public"."planet_osm_polygon" USING btree ("way");


CREATE TABLE IF NOT EXISTS "public"."planet_osm_roads" (
    "osm_id" bigint,
    "access" text,
    "addr:housename" text,
    "addr:housenumber" text,
    "addr:interpolation" text,
    "admin_level" text,
    "aerialway" text,
    "aeroway" text,
    "amenity" text,
    "barrier" text,
    "bicycle" text,
    "bridge" text,
    "boundary" text,
    "building" text,
    "construction" text,
    "covered" text,
    "foot" text,
    "highway" text,
    "historic" text,
    "horse" text,
    "junction" text,
    "landuse" text,
    "layer" integer,
    "leisure" text,
    "lock" text,
    "man_made" text,
    "military" text,
    "name" text,
    "natural" text,
    "oneway" text,
    "place" text,
    "power" text,
    "railway" text,
    "ref" text,
    "religion" text,
    "route" text,
    "service" text,
    "shop" text,
    "surface" text,
    "tourism" text,
    "tracktype" text,
    "tunnel" text,
    "water" text,
    "waterway" text,
    "way_area" real,
    "z_order" integer,
    "tags" hstore,
    "way" geometry(LineString,3857),
    "valid_since" date,
    "valid_until" date
) WITH (oids = false);

CREATE INDEX "planet_osm_roads_index" ON "public"."planet_osm_roads" USING btree ("way");
