# Generated by Django 3.0.3 on 2020-05-21 05:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ohdm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OhdmGeoobjectLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geoobject_id", models.BigIntegerField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "classification_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classification_subclassname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True, null=True
                    ),
                ),
                ("valid_since", models.DateField()),
                ("valid_until", models.DateField()),
                ("way", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "ohdm_lines",},
        ),
        migrations.CreateModel(
            name="OhdmGeoobjectPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geoobject_id", models.BigIntegerField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "classification_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classification_subclassname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True, null=True
                    ),
                ),
                ("valid_since", models.DateField()),
                ("valid_until", models.DateField()),
                ("way", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "ohdm_points",},
        ),
        migrations.CreateModel(
            name="OhdmGeoobjectPolygon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geoobject_id", models.BigIntegerField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "classification_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classification_subclassname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True, null=True
                    ),
                ),
                ("valid_since", models.DateField()),
                ("valid_until", models.DateField()),
                ("way", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "ohdm_polygons",},
        ),
        migrations.DeleteModel(name="OhdmGeoobjectWay",),
        migrations.DeleteModel(name="TileCache",),
        migrations.AlterField(
            model_name="planetosmrels",
            name="inner_members",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="planetosmrels",
            name="outer_members",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(), default=list, size=None
            ),
        ),
    ]
