# Generated by Django 3.0.3 on 2020-04-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohdm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohdmgeoobjectway',
            name='role',
        ),
    ]
