# Generated by Django 3.0.3 on 2020-02-28 13:51

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OhdmGeoobjectWay',
            fields=[
                ('way_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geoobject_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('classification_class', models.CharField(max_length=255)),
                ('classification_subclassname', models.CharField(max_length=255)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('valid_since', models.DateField()),
                ('valid_until', models.DateField()),
                ('way', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='planetosmline',
            name='geoobject',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planetosmpoint',
            name='geoobject',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planetosmpolygon',
            name='geoobject',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planetosmroads',
            name='geoobject',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
