# Generated by Django 3.0.3 on 2020-04-22 17:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohdm', '0002_remove_ohdmgeoobjectway_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetosmrels',
            name='inner_members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='planetosmrels',
            name='outer_members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
    ]
