# https://hub.docker.com/_/ubuntu
# get Ubuntu 18.04
FROM ubuntu:bionic

# Update cache and install dependencies
# find packages on https://pkgs.org/
RUN apt-get update -y && apt-get install -y \
    fonts-dejavu-core \
    fonts-hanazono \
    fonts-noto-cjk \
    fonts-noto-cjk-extra \
    fonts-noto-color-emoji \
    fonts-noto-hinted \
    fonts-noto-unhinted \
    fontconfig \
    git \
    libmapnik3.0 \
    libmapnik-dev \
    mapnik-utils \
    npm \
    nodejs \
    psf-unifont \
    python3-mapnik \
    python3-pip \
    ttf-unifont \
    typecatcher \
    unifont \
    xfonts-unifont

# install Noto Sans fonts
RUN git clone https://github.com/googlei18n/noto-emoji.git /opt/noto-emoji && \
    cp /opt/noto-emoji/fonts/NotoEmoji-Regular.ttf /usr/share/fonts/truetype/noto/NotoEmoji-Regular.ttf && \
    fc-cache -fv && \
    fc-list && \
    rm -r /opt/noto-emoji

# set python 3.x as default
RUN ln -sfn /usr/bin/python3 /usr/bin/python

# set nodejs to stable
RUN npm install -g n stable

# install cartoCSS -> https://github.com/mapbox/carto
ARG CARTO_VERSION
RUN npm install -g carto@$CARTO_VERSION

# install millstone
RUN npm install -g millstone

# https://github.com/gravitystorm/openstreetmap-carto
ARG OSM_CARTO_VERSION
RUN git clone https://github.com/gravitystorm/openstreetmap-carto.git /opt/openstreetmap-carto  && \
    cd /opt/openstreetmap-carto && \
    git fetch --all && \
    git checkout $OSM_CARTO_VERSION && \
    ./scripts/get-shapefiles.py

ADD requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

ADD date_template_importer.py /date_template_importer.py

RUN python3 /date_template_importer.py -i /opt/openstreetmap-carto/project.mml -o /opt/openstreetmap-carto/style.mml
RUN carto /opt/openstreetmap-carto/style.mml > /opt/openstreetmap-carto/style.xml

WORKDIR /app

# enable port 5000 for nginx proxy
EXPOSE 5000

# Clean up APT
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
